keys:
  - &host_darkhero_persist age1sply9vlhfpdsf225aent3qxx8x0p38nqwwkly4vl9dpn0zyatsrqupu3rh
  - &user_darkhero age18p5x7dlqf285g9jwv0pchvkwqj2ucfkva90r4f7kyz3jfz0xcyeqxem53g
  - &yubikey_vovin age1yubikey1qvwfugppvzvlwvcmcwfr35vru8gh6607pnemjf0rtvjd5y5xlnsezkr6p4x

creation_rules:
  - path_regex: secrets/.*\.sops\.yaml$
    key_groups:
      - age:
          - *host_darkhero_persist
          - *user_darkhero
          - *yubikey_vovin
